#!/usr/bin/env python3
"""Build the OpenCL kernel source and embed it in a C++ header.

kernels.cl is hand-written except for one placeholder, @MALTA_UNITS@, which is
filled with the bodies of butteraugli's two MaltaUnit overloads lifted verbatim
from butteraugli.cc. Those bodies are ~500 lines of straight-line float
arithmetic over d[...]; transcribing them by hand would be a reliable source of
silent one-character errors, and lifting them means a change upstream cannot
drift away from the port unnoticed.

The expansion is written to kernels_gen.cl (which is what the runtime loads,
directly when CLBA_KERNEL_DIR is set, otherwise from the generated header).

Run from anywhere; paths are resolved relative to this script.
"""
import os
import re
import sys

here = os.path.dirname(os.path.abspath(__file__))
cl_src = os.path.join(here, 'kernels.cl')
cl_gen = os.path.join(here, 'kernels_gen.cl')
ba_src = os.path.join(here, os.pardir, 'guetzli', 'third_party', 'butteraugli',
                      'butteraugli', 'butteraugli.cc')
dst = os.path.join(here, 'clba_kernels.h')


def extract_body(text, tag):
    """Return the brace-enclosed body of MaltaUnit(tag, ...)."""
    m = re.search(r'static float MaltaUnit\(' + tag + r',(?:[^{])*\{', text)
    if not m:
        sys.exit('MaltaUnit(%s, ...) not found in butteraugli.cc' % tag)
    start = m.end() - 1
    depth = 0
    for i in range(start, len(text)):
        if text[i] == '{':
            depth += 1
        elif text[i] == '}':
            depth -= 1
            if depth == 0:
                return text[start:i + 1]
    sys.exit('unbalanced braces in MaltaUnit(%s, ...)' % tag)


def check_translatable(body, tag):
    """The bodies are only safe to lift if they are pure float arithmetic.

    Anything else -- a std:: call, a libm call, a double -- would need a
    deliberate decision about how to evaluate it on a device with no fp64, so
    refuse to generate rather than translate it silently.
    """
    stripped = re.sub(r'//[^\n]*', '', body)
    ok = set(['float', 'int', 'const', 'return', 'd', 'xs', 'xs3', 'sum',
              'retval'])
    for ident in set(re.findall(r'[A-Za-z_][A-Za-z_0-9]*', stripped)):
        if ident in ok or re.match(r'^_+[0-9_]*$', ident):
            continue
        sys.exit('MaltaUnit(%s) uses %r, which this generator will not '
                 'translate blindly' % (tag, ident))
    # Every subscript must stay inside the +-4 stencil the padded layout
    # assumes; see the comment on malta_apply in kernels.cl.
    for expr in re.findall(r'd\[([^\]]*)\]', stripped):
        e = expr.replace(' ', '').replace('xs3', '(3*xs)')
        a, b = eval(e, {'xs': 1000000}), eval(e, {'xs': 2000000})
        dy = (b - a) // 1000000
        dx = a - dy * 1000000
        if abs(dx) > 4 or abs(dy) > 4:
            sys.exit('MaltaUnit(%s) reads d[%s] = (%+d,%+d), outside the '
                     '9x9 stencil the padded layout assumes' %
                     (tag, expr, dx, dy))


ba_text = open(ba_src).read()
units = []
for tag, name in (('MaltaTag', 'malta_unit_hf'), ('MaltaTagLF',
                                                  'malta_unit_lf')):
    body = extract_body(ba_text, tag)
    check_translatable(body, tag)
    units.append('// Lifted verbatim from MaltaUnit(%s, ...) in butteraugli.cc'
                 ' by gen_kernels.py.\n'
                 'static float %s(__global const float* restrict d,\n'
                 '                const int xs) %s' % (tag, name, body))
malta = '\n\n'.join(units)

text = open(cl_src).read()
if '@MALTA_UNITS@' not in text:
    sys.exit('kernels.cl has no @MALTA_UNITS@ placeholder')
text = text.replace('@MALTA_UNITS@', malta)

with open(cl_gen, 'w') as f:
    f.write('// Generated by gen_kernels.py from kernels.cl. Do not edit.\n')
    f.write(text)

delim = 'CLBASRC'
if ')' + delim + '"' in text:
    sys.exit('kernel source contains the raw-string delimiter %r' % delim)

with open(dst, 'w') as f:
    f.write('// Generated by gen_kernels.py from kernels.cl. Do not edit.\n')
    f.write('#ifndef CLBUTTERAUGLI_CLBA_KERNELS_H_\n')
    f.write('#define CLBUTTERAUGLI_CLBA_KERNELS_H_\n\n')
    f.write('static const char* const kCLBAKernelSource = R"%s(\n' % delim)
    f.write(text)
    f.write(')%s";\n\n' % delim)
    f.write('#endif  // CLBUTTERAUGLI_CLBA_KERNELS_H_\n')

print('wrote %s and %s (%d bytes, %d lifted from butteraugli.cc)' %
      (os.path.basename(cl_gen), os.path.basename(dst), len(text), len(malta)))
